package cn.com.loan.dao;

import cn.com.loan.pojo.PrequsetLog;
import cn.com.loan.pojo.PrequsetLogExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface PrequsetLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_request_log
     *
     * @mbggenerated
     */
    int countByExample(PrequsetLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_request_log
     *
     * @mbggenerated
     */
    int deleteByExample(PrequsetLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_request_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_request_log
     *
     * @mbggenerated
     */
    int insert(PrequsetLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_request_log
     *
     * @mbggenerated
     */
    int insertSelective(PrequsetLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_request_log
     *
     * @mbggenerated
     */
    List<PrequsetLog> selectByExample(PrequsetLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_request_log
     *
     * @mbggenerated
     */
    PrequsetLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_request_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PrequsetLog record, @Param("example") PrequsetLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_request_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PrequsetLog record, @Param("example") PrequsetLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_request_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PrequsetLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_request_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PrequsetLog record);
}