package cn.com.loan.dao;

import cn.com.loan.pojo.TestData;
import cn.com.loan.pojo.TestDataExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TestDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_data
     *
     * @mbggenerated
     */
    int countByExample(TestDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_data
     *
     * @mbggenerated
     */
    int deleteByExample(TestDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_data
     *
     * @mbggenerated
     */
    int insert(TestData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_data
     *
     * @mbggenerated
     */
    int insertSelective(TestData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_data
     *
     * @mbggenerated
     */
    List<TestData> selectByExample(TestDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_data
     *
     * @mbggenerated
     */
    TestData selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_data
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TestData record, @Param("example") TestDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_data
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TestData record, @Param("example") TestDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TestData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TestData record);
}