package cn.com.loan.dao;

import cn.com.loan.pojo.WpersonalInfo;
import cn.com.loan.pojo.WpersonalInfoExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface WpersonalInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_personal_info
     *
     * @mbggenerated
     */
    int countByExample(WpersonalInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_personal_info
     *
     * @mbggenerated
     */
    int deleteByExample(WpersonalInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_personal_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_personal_info
     *
     * @mbggenerated
     */
    int insert(WpersonalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_personal_info
     *
     * @mbggenerated
     */
    int insertSelective(WpersonalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_personal_info
     *
     * @mbggenerated
     */
    List<WpersonalInfo> selectByExample(WpersonalInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_personal_info
     *
     * @mbggenerated
     */
    WpersonalInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_personal_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WpersonalInfo record, @Param("example") WpersonalInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_personal_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WpersonalInfo record, @Param("example") WpersonalInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_personal_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WpersonalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_personal_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WpersonalInfo record);
}