package cn.com.loan.dao;

import cn.com.loan.pojo.WsendIdentyCodeLog;
import cn.com.loan.pojo.WsendIdentyCodeLogExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface WsendIdentyCodeLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sendIdentyCode_log
     *
     * @mbggenerated
     */
    int countByExample(WsendIdentyCodeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sendIdentyCode_log
     *
     * @mbggenerated
     */
    int deleteByExample(WsendIdentyCodeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sendIdentyCode_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sendIdentyCode_log
     *
     * @mbggenerated
     */
    int insert(WsendIdentyCodeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sendIdentyCode_log
     *
     * @mbggenerated
     */
    int insertSelective(WsendIdentyCodeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sendIdentyCode_log
     *
     * @mbggenerated
     */
    List<WsendIdentyCodeLog> selectByExample(WsendIdentyCodeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sendIdentyCode_log
     *
     * @mbggenerated
     */
    WsendIdentyCodeLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sendIdentyCode_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WsendIdentyCodeLog record, @Param("example") WsendIdentyCodeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sendIdentyCode_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WsendIdentyCodeLog record, @Param("example") WsendIdentyCodeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sendIdentyCode_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WsendIdentyCodeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sendIdentyCode_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WsendIdentyCodeLog record);
}