package cn.com.loan.pojo;

import java.io.Serializable;
import java.util.Date;

public class PrequsetLog implements Serializable{
    /**
	  * @Fields serialVersionUID : TODO（用一句话描述这个变量表示什么）
	  */
	
	private static final long serialVersionUID = 4770361034509692724L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_request_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_request_log.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_request_log.hostName
     *
     * @mbggenerated
     */
    private String hostname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_request_log.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_request_log.userId
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_request_log.userName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_request_log.thread
     *
     * @mbggenerated
     */
    private String thread;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_request_log.withTime
     *
     * @mbggenerated
     */
    private String withtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_request_log.paramsStr
     *
     * @mbggenerated
     */
    private String paramsstr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_request_log.id
     *
     * @return the value of p_request_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_request_log.id
     *
     * @param id the value for p_request_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_request_log.createTime
     *
     * @return the value of p_request_log.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_request_log.createTime
     *
     * @param createtime the value for p_request_log.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_request_log.hostName
     *
     * @return the value of p_request_log.hostName
     *
     * @mbggenerated
     */
    public String getHostname() {
        return hostname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_request_log.hostName
     *
     * @param hostname the value for p_request_log.hostName
     *
     * @mbggenerated
     */
    public void setHostname(String hostname) {
        this.hostname = hostname == null ? null : hostname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_request_log.url
     *
     * @return the value of p_request_log.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_request_log.url
     *
     * @param url the value for p_request_log.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_request_log.userId
     *
     * @return the value of p_request_log.userId
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_request_log.userId
     *
     * @param userid the value for p_request_log.userId
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_request_log.userName
     *
     * @return the value of p_request_log.userName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_request_log.userName
     *
     * @param username the value for p_request_log.userName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_request_log.thread
     *
     * @return the value of p_request_log.thread
     *
     * @mbggenerated
     */
    public String getThread() {
        return thread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_request_log.thread
     *
     * @param thread the value for p_request_log.thread
     *
     * @mbggenerated
     */
    public void setThread(String thread) {
        this.thread = thread == null ? null : thread.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_request_log.withTime
     *
     * @return the value of p_request_log.withTime
     *
     * @mbggenerated
     */
    public String getWithtime() {
        return withtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_request_log.withTime
     *
     * @param withtime the value for p_request_log.withTime
     *
     * @mbggenerated
     */
    public void setWithtime(String withtime) {
        this.withtime = withtime == null ? null : withtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_request_log.paramsStr
     *
     * @return the value of p_request_log.paramsStr
     *
     * @mbggenerated
     */
    public String getParamsstr() {
        return paramsstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_request_log.paramsStr
     *
     * @param paramsstr the value for p_request_log.paramsStr
     *
     * @mbggenerated
     */
    public void setParamsstr(String paramsstr) {
        this.paramsstr = paramsstr == null ? null : paramsstr.trim();
    }
}