package cn.com.loan.pojo;

import java.io.Serializable;

public class Region implements Serializable {
	/**
	  * @Fields serialVersionUID : 序列化id
	  */
	private static final long serialVersionUID = -7763921631323906384L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region.regionname
     *
     * @mbggenerated
     */
    private String regionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region.parentregionid
     *
     * @mbggenerated
     */
    private String parentregionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region.regioncode
     *
     * @mbggenerated
     */
    private String regioncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region.regiongrade
     *
     * @mbggenerated
     */
    private String regiongrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region.provincialcapital
     *
     * @mbggenerated
     */
    private Integer provincialcapital;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region.id
     *
     * @return the value of t_region.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region.id
     *
     * @param id the value for t_region.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region.regionname
     *
     * @return the value of t_region.regionname
     *
     * @mbggenerated
     */
    public String getRegionname() {
        return regionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region.regionname
     *
     * @param regionname the value for t_region.regionname
     *
     * @mbggenerated
     */
    public void setRegionname(String regionname) {
        this.regionname = regionname == null ? null : regionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region.parentregionid
     *
     * @return the value of t_region.parentregionid
     *
     * @mbggenerated
     */
    public String getParentregionid() {
        return parentregionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region.parentregionid
     *
     * @param parentregionid the value for t_region.parentregionid
     *
     * @mbggenerated
     */
    public void setParentregionid(String parentregionid) {
        this.parentregionid = parentregionid == null ? null : parentregionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region.regioncode
     *
     * @return the value of t_region.regioncode
     *
     * @mbggenerated
     */
    public String getRegioncode() {
        return regioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region.regioncode
     *
     * @param regioncode the value for t_region.regioncode
     *
     * @mbggenerated
     */
    public void setRegioncode(String regioncode) {
        this.regioncode = regioncode == null ? null : regioncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region.regiongrade
     *
     * @return the value of t_region.regiongrade
     *
     * @mbggenerated
     */
    public String getRegiongrade() {
        return regiongrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region.regiongrade
     *
     * @param regiongrade the value for t_region.regiongrade
     *
     * @mbggenerated
     */
    public void setRegiongrade(String regiongrade) {
        this.regiongrade = regiongrade == null ? null : regiongrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region.provincialcapital
     *
     * @return the value of t_region.provincialcapital
     *
     * @mbggenerated
     */
    public Integer getProvincialcapital() {
        return provincialcapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region.provincialcapital
     *
     * @param provincialcapital the value for t_region.provincialcapital
     *
     * @mbggenerated
     */
    public void setProvincialcapital(Integer provincialcapital) {
        this.provincialcapital = provincialcapital;
    }

 
    
}