package cn.com.loan.pojo;

import java.io.Serializable;

public class TestData implements Serializable {
	/**
	  * @Fields serialVersionUID : 序列化id
	  */
	private static final long serialVersionUID = 2029996481333455098L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_data.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_data.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_data.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_data.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_data.id
     *
     * @return the value of t_test_data.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_data.id
     *
     * @param id the value for t_test_data.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_data.name
     *
     * @return the value of t_test_data.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_data.name
     *
     * @param name the value for t_test_data.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_data.code
     *
     * @return the value of t_test_data.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_data.code
     *
     * @param code the value for t_test_data.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_data.num
     *
     * @return the value of t_test_data.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_data.num
     *
     * @param num the value for t_test_data.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }
}