package cn.com.loan.pojo;

import java.util.Date;

public class WloginInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_login_info.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_login_info.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_login_info.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_login_info.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_login_info.login_password
     *
     * @mbggenerated
     */
    private String loginPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_login_info.pay_password
     *
     * @mbggenerated
     */
    private String payPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_login_info.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_login_info.ctreatetime
     *
     * @mbggenerated
     */
    private Date ctreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_login_info.origin
     *
     * @mbggenerated
     */
    private String origin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_login_info.id
     *
     * @return the value of w_login_info.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_login_info.id
     *
     * @param id the value for w_login_info.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_login_info.username
     *
     * @return the value of w_login_info.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_login_info.username
     *
     * @param username the value for w_login_info.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_login_info.phone
     *
     * @return the value of w_login_info.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_login_info.phone
     *
     * @param phone the value for w_login_info.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_login_info.email
     *
     * @return the value of w_login_info.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_login_info.email
     *
     * @param email the value for w_login_info.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_login_info.login_password
     *
     * @return the value of w_login_info.login_password
     *
     * @mbggenerated
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_login_info.login_password
     *
     * @param loginPassword the value for w_login_info.login_password
     *
     * @mbggenerated
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_login_info.pay_password
     *
     * @return the value of w_login_info.pay_password
     *
     * @mbggenerated
     */
    public String getPayPassword() {
        return payPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_login_info.pay_password
     *
     * @param payPassword the value for w_login_info.pay_password
     *
     * @mbggenerated
     */
    public void setPayPassword(String payPassword) {
        this.payPassword = payPassword == null ? null : payPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_login_info.status
     *
     * @return the value of w_login_info.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_login_info.status
     *
     * @param status the value for w_login_info.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_login_info.ctreatetime
     *
     * @return the value of w_login_info.ctreatetime
     *
     * @mbggenerated
     */
    public Date getCtreatetime() {
        return ctreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_login_info.ctreatetime
     *
     * @param ctreatetime the value for w_login_info.ctreatetime
     *
     * @mbggenerated
     */
    public void setCtreatetime(Date ctreatetime) {
        this.ctreatetime = ctreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_login_info.origin
     *
     * @return the value of w_login_info.origin
     *
     * @mbggenerated
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_login_info.origin
     *
     * @param origin the value for w_login_info.origin
     *
     * @mbggenerated
     */
    public void setOrigin(String origin) {
        this.origin = origin == null ? null : origin.trim();
    }
}