package cn.com.loan.pojo;

public class WpersonalInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.login_id
     *
     * @mbggenerated
     */
    private String loginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.sexual
     *
     * @mbggenerated
     */
    private String sexual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.born_date
     *
     * @mbggenerated
     */
    private String bornDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.contact
     *
     * @mbggenerated
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.marital_status
     *
     * @mbggenerated
     */
    private String maritalStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.children_status
     *
     * @mbggenerated
     */
    private String childrenStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.endowment insurance_status
     *
     * @mbggenerated
     */
    private String endowmentInsuranceStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.life_insurance_status
     *
     * @mbggenerated
     */
    private String lifeInsuranceStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.employment_type
     *
     * @mbggenerated
     */
    private String employmentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.highest_education
     *
     * @mbggenerated
     */
    private String highestEducation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.residence_address
     *
     * @mbggenerated
     */
    private String residenceAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.certificate_address
     *
     * @mbggenerated
     */
    private String certificateAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.register_desc
     *
     * @mbggenerated
     */
    private String registerDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.frozen_status
     *
     * @mbggenerated
     */
    private String frozenStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.derict_relations_one_name
     *
     * @mbggenerated
     */
    private String derictRelationsOneName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.derict_relations_one_id
     *
     * @mbggenerated
     */
    private String derictRelationsOneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.derict_relations_one_phone
     *
     * @mbggenerated
     */
    private String derictRelationsOnePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.derict_relations_two_name
     *
     * @mbggenerated
     */
    private String derictRelationsTwoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.derict_relations_two_id
     *
     * @mbggenerated
     */
    private String derictRelationsTwoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.derict_relations_two_phone
     *
     * @mbggenerated
     */
    private String derictRelationsTwoPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.relations_one_name
     *
     * @mbggenerated
     */
    private String relationsOneName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.relations_one_id
     *
     * @mbggenerated
     */
    private String relationsOneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.relations_one_phone
     *
     * @mbggenerated
     */
    private String relationsOnePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.relations_two_name
     *
     * @mbggenerated
     */
    private String relationsTwoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.relations_two_id
     *
     * @mbggenerated
     */
    private String relationsTwoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.relations_two_phone
     *
     * @mbggenerated
     */
    private String relationsTwoPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.certificate_no
     *
     * @mbggenerated
     */
    private String certificateNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_personal_info.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.id
     *
     * @return the value of w_personal_info.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.id
     *
     * @param id the value for w_personal_info.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.login_id
     *
     * @return the value of w_personal_info.login_id
     *
     * @mbggenerated
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.login_id
     *
     * @param loginId the value for w_personal_info.login_id
     *
     * @mbggenerated
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId == null ? null : loginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.sexual
     *
     * @return the value of w_personal_info.sexual
     *
     * @mbggenerated
     */
    public String getSexual() {
        return sexual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.sexual
     *
     * @param sexual the value for w_personal_info.sexual
     *
     * @mbggenerated
     */
    public void setSexual(String sexual) {
        this.sexual = sexual == null ? null : sexual.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.born_date
     *
     * @return the value of w_personal_info.born_date
     *
     * @mbggenerated
     */
    public String getBornDate() {
        return bornDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.born_date
     *
     * @param bornDate the value for w_personal_info.born_date
     *
     * @mbggenerated
     */
    public void setBornDate(String bornDate) {
        this.bornDate = bornDate == null ? null : bornDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.contact
     *
     * @return the value of w_personal_info.contact
     *
     * @mbggenerated
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.contact
     *
     * @param contact the value for w_personal_info.contact
     *
     * @mbggenerated
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.marital_status
     *
     * @return the value of w_personal_info.marital_status
     *
     * @mbggenerated
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.marital_status
     *
     * @param maritalStatus the value for w_personal_info.marital_status
     *
     * @mbggenerated
     */
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus == null ? null : maritalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.children_status
     *
     * @return the value of w_personal_info.children_status
     *
     * @mbggenerated
     */
    public String getChildrenStatus() {
        return childrenStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.children_status
     *
     * @param childrenStatus the value for w_personal_info.children_status
     *
     * @mbggenerated
     */
    public void setChildrenStatus(String childrenStatus) {
        this.childrenStatus = childrenStatus == null ? null : childrenStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.endowment insurance_status
     *
     * @return the value of w_personal_info.endowment insurance_status
     *
     * @mbggenerated
     */
    public String getEndowmentInsuranceStatus() {
        return endowmentInsuranceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.endowment insurance_status
     *
     * @param endowmentInsuranceStatus the value for w_personal_info.endowment insurance_status
     *
     * @mbggenerated
     */
    public void setEndowmentInsuranceStatus(String endowmentInsuranceStatus) {
        this.endowmentInsuranceStatus = endowmentInsuranceStatus == null ? null : endowmentInsuranceStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.life_insurance_status
     *
     * @return the value of w_personal_info.life_insurance_status
     *
     * @mbggenerated
     */
    public String getLifeInsuranceStatus() {
        return lifeInsuranceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.life_insurance_status
     *
     * @param lifeInsuranceStatus the value for w_personal_info.life_insurance_status
     *
     * @mbggenerated
     */
    public void setLifeInsuranceStatus(String lifeInsuranceStatus) {
        this.lifeInsuranceStatus = lifeInsuranceStatus == null ? null : lifeInsuranceStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.employment_type
     *
     * @return the value of w_personal_info.employment_type
     *
     * @mbggenerated
     */
    public String getEmploymentType() {
        return employmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.employment_type
     *
     * @param employmentType the value for w_personal_info.employment_type
     *
     * @mbggenerated
     */
    public void setEmploymentType(String employmentType) {
        this.employmentType = employmentType == null ? null : employmentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.highest_education
     *
     * @return the value of w_personal_info.highest_education
     *
     * @mbggenerated
     */
    public String getHighestEducation() {
        return highestEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.highest_education
     *
     * @param highestEducation the value for w_personal_info.highest_education
     *
     * @mbggenerated
     */
    public void setHighestEducation(String highestEducation) {
        this.highestEducation = highestEducation == null ? null : highestEducation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.residence_address
     *
     * @return the value of w_personal_info.residence_address
     *
     * @mbggenerated
     */
    public String getResidenceAddress() {
        return residenceAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.residence_address
     *
     * @param residenceAddress the value for w_personal_info.residence_address
     *
     * @mbggenerated
     */
    public void setResidenceAddress(String residenceAddress) {
        this.residenceAddress = residenceAddress == null ? null : residenceAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.certificate_address
     *
     * @return the value of w_personal_info.certificate_address
     *
     * @mbggenerated
     */
    public String getCertificateAddress() {
        return certificateAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.certificate_address
     *
     * @param certificateAddress the value for w_personal_info.certificate_address
     *
     * @mbggenerated
     */
    public void setCertificateAddress(String certificateAddress) {
        this.certificateAddress = certificateAddress == null ? null : certificateAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.register_desc
     *
     * @return the value of w_personal_info.register_desc
     *
     * @mbggenerated
     */
    public String getRegisterDesc() {
        return registerDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.register_desc
     *
     * @param registerDesc the value for w_personal_info.register_desc
     *
     * @mbggenerated
     */
    public void setRegisterDesc(String registerDesc) {
        this.registerDesc = registerDesc == null ? null : registerDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.frozen_status
     *
     * @return the value of w_personal_info.frozen_status
     *
     * @mbggenerated
     */
    public String getFrozenStatus() {
        return frozenStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.frozen_status
     *
     * @param frozenStatus the value for w_personal_info.frozen_status
     *
     * @mbggenerated
     */
    public void setFrozenStatus(String frozenStatus) {
        this.frozenStatus = frozenStatus == null ? null : frozenStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.derict_relations_one_name
     *
     * @return the value of w_personal_info.derict_relations_one_name
     *
     * @mbggenerated
     */
    public String getDerictRelationsOneName() {
        return derictRelationsOneName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.derict_relations_one_name
     *
     * @param derictRelationsOneName the value for w_personal_info.derict_relations_one_name
     *
     * @mbggenerated
     */
    public void setDerictRelationsOneName(String derictRelationsOneName) {
        this.derictRelationsOneName = derictRelationsOneName == null ? null : derictRelationsOneName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.derict_relations_one_id
     *
     * @return the value of w_personal_info.derict_relations_one_id
     *
     * @mbggenerated
     */
    public String getDerictRelationsOneId() {
        return derictRelationsOneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.derict_relations_one_id
     *
     * @param derictRelationsOneId the value for w_personal_info.derict_relations_one_id
     *
     * @mbggenerated
     */
    public void setDerictRelationsOneId(String derictRelationsOneId) {
        this.derictRelationsOneId = derictRelationsOneId == null ? null : derictRelationsOneId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.derict_relations_one_phone
     *
     * @return the value of w_personal_info.derict_relations_one_phone
     *
     * @mbggenerated
     */
    public String getDerictRelationsOnePhone() {
        return derictRelationsOnePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.derict_relations_one_phone
     *
     * @param derictRelationsOnePhone the value for w_personal_info.derict_relations_one_phone
     *
     * @mbggenerated
     */
    public void setDerictRelationsOnePhone(String derictRelationsOnePhone) {
        this.derictRelationsOnePhone = derictRelationsOnePhone == null ? null : derictRelationsOnePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.derict_relations_two_name
     *
     * @return the value of w_personal_info.derict_relations_two_name
     *
     * @mbggenerated
     */
    public String getDerictRelationsTwoName() {
        return derictRelationsTwoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.derict_relations_two_name
     *
     * @param derictRelationsTwoName the value for w_personal_info.derict_relations_two_name
     *
     * @mbggenerated
     */
    public void setDerictRelationsTwoName(String derictRelationsTwoName) {
        this.derictRelationsTwoName = derictRelationsTwoName == null ? null : derictRelationsTwoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.derict_relations_two_id
     *
     * @return the value of w_personal_info.derict_relations_two_id
     *
     * @mbggenerated
     */
    public String getDerictRelationsTwoId() {
        return derictRelationsTwoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.derict_relations_two_id
     *
     * @param derictRelationsTwoId the value for w_personal_info.derict_relations_two_id
     *
     * @mbggenerated
     */
    public void setDerictRelationsTwoId(String derictRelationsTwoId) {
        this.derictRelationsTwoId = derictRelationsTwoId == null ? null : derictRelationsTwoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.derict_relations_two_phone
     *
     * @return the value of w_personal_info.derict_relations_two_phone
     *
     * @mbggenerated
     */
    public String getDerictRelationsTwoPhone() {
        return derictRelationsTwoPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.derict_relations_two_phone
     *
     * @param derictRelationsTwoPhone the value for w_personal_info.derict_relations_two_phone
     *
     * @mbggenerated
     */
    public void setDerictRelationsTwoPhone(String derictRelationsTwoPhone) {
        this.derictRelationsTwoPhone = derictRelationsTwoPhone == null ? null : derictRelationsTwoPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.relations_one_name
     *
     * @return the value of w_personal_info.relations_one_name
     *
     * @mbggenerated
     */
    public String getRelationsOneName() {
        return relationsOneName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.relations_one_name
     *
     * @param relationsOneName the value for w_personal_info.relations_one_name
     *
     * @mbggenerated
     */
    public void setRelationsOneName(String relationsOneName) {
        this.relationsOneName = relationsOneName == null ? null : relationsOneName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.relations_one_id
     *
     * @return the value of w_personal_info.relations_one_id
     *
     * @mbggenerated
     */
    public String getRelationsOneId() {
        return relationsOneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.relations_one_id
     *
     * @param relationsOneId the value for w_personal_info.relations_one_id
     *
     * @mbggenerated
     */
    public void setRelationsOneId(String relationsOneId) {
        this.relationsOneId = relationsOneId == null ? null : relationsOneId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.relations_one_phone
     *
     * @return the value of w_personal_info.relations_one_phone
     *
     * @mbggenerated
     */
    public String getRelationsOnePhone() {
        return relationsOnePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.relations_one_phone
     *
     * @param relationsOnePhone the value for w_personal_info.relations_one_phone
     *
     * @mbggenerated
     */
    public void setRelationsOnePhone(String relationsOnePhone) {
        this.relationsOnePhone = relationsOnePhone == null ? null : relationsOnePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.relations_two_name
     *
     * @return the value of w_personal_info.relations_two_name
     *
     * @mbggenerated
     */
    public String getRelationsTwoName() {
        return relationsTwoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.relations_two_name
     *
     * @param relationsTwoName the value for w_personal_info.relations_two_name
     *
     * @mbggenerated
     */
    public void setRelationsTwoName(String relationsTwoName) {
        this.relationsTwoName = relationsTwoName == null ? null : relationsTwoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.relations_two_id
     *
     * @return the value of w_personal_info.relations_two_id
     *
     * @mbggenerated
     */
    public String getRelationsTwoId() {
        return relationsTwoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.relations_two_id
     *
     * @param relationsTwoId the value for w_personal_info.relations_two_id
     *
     * @mbggenerated
     */
    public void setRelationsTwoId(String relationsTwoId) {
        this.relationsTwoId = relationsTwoId == null ? null : relationsTwoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.relations_two_phone
     *
     * @return the value of w_personal_info.relations_two_phone
     *
     * @mbggenerated
     */
    public String getRelationsTwoPhone() {
        return relationsTwoPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.relations_two_phone
     *
     * @param relationsTwoPhone the value for w_personal_info.relations_two_phone
     *
     * @mbggenerated
     */
    public void setRelationsTwoPhone(String relationsTwoPhone) {
        this.relationsTwoPhone = relationsTwoPhone == null ? null : relationsTwoPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.certificate_no
     *
     * @return the value of w_personal_info.certificate_no
     *
     * @mbggenerated
     */
    public String getCertificateNo() {
        return certificateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.certificate_no
     *
     * @param certificateNo the value for w_personal_info.certificate_no
     *
     * @mbggenerated
     */
    public void setCertificateNo(String certificateNo) {
        this.certificateNo = certificateNo == null ? null : certificateNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_personal_info.real_name
     *
     * @return the value of w_personal_info.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_personal_info.real_name
     *
     * @param realName the value for w_personal_info.real_name
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }
}