package cn.com.loan.pojo;

import java.util.ArrayList;
import java.util.List;

public class WpersonalInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_personal_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_personal_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_personal_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_personal_info
     *
     * @mbggenerated
     */
    public WpersonalInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_personal_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_personal_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_personal_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_personal_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_personal_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_personal_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_personal_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_personal_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_personal_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_personal_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table w_personal_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLoginIdIsNull() {
            addCriterion("login_id is null");
            return (Criteria) this;
        }

        public Criteria andLoginIdIsNotNull() {
            addCriterion("login_id is not null");
            return (Criteria) this;
        }

        public Criteria andLoginIdEqualTo(String value) {
            addCriterion("login_id =", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdNotEqualTo(String value) {
            addCriterion("login_id <>", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdGreaterThan(String value) {
            addCriterion("login_id >", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdGreaterThanOrEqualTo(String value) {
            addCriterion("login_id >=", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdLessThan(String value) {
            addCriterion("login_id <", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdLessThanOrEqualTo(String value) {
            addCriterion("login_id <=", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdLike(String value) {
            addCriterion("login_id like", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdNotLike(String value) {
            addCriterion("login_id not like", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdIn(List<String> values) {
            addCriterion("login_id in", values, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdNotIn(List<String> values) {
            addCriterion("login_id not in", values, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdBetween(String value1, String value2) {
            addCriterion("login_id between", value1, value2, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdNotBetween(String value1, String value2) {
            addCriterion("login_id not between", value1, value2, "loginId");
            return (Criteria) this;
        }

        public Criteria andSexualIsNull() {
            addCriterion("sexual is null");
            return (Criteria) this;
        }

        public Criteria andSexualIsNotNull() {
            addCriterion("sexual is not null");
            return (Criteria) this;
        }

        public Criteria andSexualEqualTo(String value) {
            addCriterion("sexual =", value, "sexual");
            return (Criteria) this;
        }

        public Criteria andSexualNotEqualTo(String value) {
            addCriterion("sexual <>", value, "sexual");
            return (Criteria) this;
        }

        public Criteria andSexualGreaterThan(String value) {
            addCriterion("sexual >", value, "sexual");
            return (Criteria) this;
        }

        public Criteria andSexualGreaterThanOrEqualTo(String value) {
            addCriterion("sexual >=", value, "sexual");
            return (Criteria) this;
        }

        public Criteria andSexualLessThan(String value) {
            addCriterion("sexual <", value, "sexual");
            return (Criteria) this;
        }

        public Criteria andSexualLessThanOrEqualTo(String value) {
            addCriterion("sexual <=", value, "sexual");
            return (Criteria) this;
        }

        public Criteria andSexualLike(String value) {
            addCriterion("sexual like", value, "sexual");
            return (Criteria) this;
        }

        public Criteria andSexualNotLike(String value) {
            addCriterion("sexual not like", value, "sexual");
            return (Criteria) this;
        }

        public Criteria andSexualIn(List<String> values) {
            addCriterion("sexual in", values, "sexual");
            return (Criteria) this;
        }

        public Criteria andSexualNotIn(List<String> values) {
            addCriterion("sexual not in", values, "sexual");
            return (Criteria) this;
        }

        public Criteria andSexualBetween(String value1, String value2) {
            addCriterion("sexual between", value1, value2, "sexual");
            return (Criteria) this;
        }

        public Criteria andSexualNotBetween(String value1, String value2) {
            addCriterion("sexual not between", value1, value2, "sexual");
            return (Criteria) this;
        }

        public Criteria andBornDateIsNull() {
            addCriterion("born_date is null");
            return (Criteria) this;
        }

        public Criteria andBornDateIsNotNull() {
            addCriterion("born_date is not null");
            return (Criteria) this;
        }

        public Criteria andBornDateEqualTo(String value) {
            addCriterion("born_date =", value, "bornDate");
            return (Criteria) this;
        }

        public Criteria andBornDateNotEqualTo(String value) {
            addCriterion("born_date <>", value, "bornDate");
            return (Criteria) this;
        }

        public Criteria andBornDateGreaterThan(String value) {
            addCriterion("born_date >", value, "bornDate");
            return (Criteria) this;
        }

        public Criteria andBornDateGreaterThanOrEqualTo(String value) {
            addCriterion("born_date >=", value, "bornDate");
            return (Criteria) this;
        }

        public Criteria andBornDateLessThan(String value) {
            addCriterion("born_date <", value, "bornDate");
            return (Criteria) this;
        }

        public Criteria andBornDateLessThanOrEqualTo(String value) {
            addCriterion("born_date <=", value, "bornDate");
            return (Criteria) this;
        }

        public Criteria andBornDateLike(String value) {
            addCriterion("born_date like", value, "bornDate");
            return (Criteria) this;
        }

        public Criteria andBornDateNotLike(String value) {
            addCriterion("born_date not like", value, "bornDate");
            return (Criteria) this;
        }

        public Criteria andBornDateIn(List<String> values) {
            addCriterion("born_date in", values, "bornDate");
            return (Criteria) this;
        }

        public Criteria andBornDateNotIn(List<String> values) {
            addCriterion("born_date not in", values, "bornDate");
            return (Criteria) this;
        }

        public Criteria andBornDateBetween(String value1, String value2) {
            addCriterion("born_date between", value1, value2, "bornDate");
            return (Criteria) this;
        }

        public Criteria andBornDateNotBetween(String value1, String value2) {
            addCriterion("born_date not between", value1, value2, "bornDate");
            return (Criteria) this;
        }

        public Criteria andContactIsNull() {
            addCriterion("contact is null");
            return (Criteria) this;
        }

        public Criteria andContactIsNotNull() {
            addCriterion("contact is not null");
            return (Criteria) this;
        }

        public Criteria andContactEqualTo(String value) {
            addCriterion("contact =", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactNotEqualTo(String value) {
            addCriterion("contact <>", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactGreaterThan(String value) {
            addCriterion("contact >", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactGreaterThanOrEqualTo(String value) {
            addCriterion("contact >=", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactLessThan(String value) {
            addCriterion("contact <", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactLessThanOrEqualTo(String value) {
            addCriterion("contact <=", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactLike(String value) {
            addCriterion("contact like", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactNotLike(String value) {
            addCriterion("contact not like", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactIn(List<String> values) {
            addCriterion("contact in", values, "contact");
            return (Criteria) this;
        }

        public Criteria andContactNotIn(List<String> values) {
            addCriterion("contact not in", values, "contact");
            return (Criteria) this;
        }

        public Criteria andContactBetween(String value1, String value2) {
            addCriterion("contact between", value1, value2, "contact");
            return (Criteria) this;
        }

        public Criteria andContactNotBetween(String value1, String value2) {
            addCriterion("contact not between", value1, value2, "contact");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusIsNull() {
            addCriterion("marital_status is null");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusIsNotNull() {
            addCriterion("marital_status is not null");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusEqualTo(String value) {
            addCriterion("marital_status =", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusNotEqualTo(String value) {
            addCriterion("marital_status <>", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusGreaterThan(String value) {
            addCriterion("marital_status >", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusGreaterThanOrEqualTo(String value) {
            addCriterion("marital_status >=", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusLessThan(String value) {
            addCriterion("marital_status <", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusLessThanOrEqualTo(String value) {
            addCriterion("marital_status <=", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusLike(String value) {
            addCriterion("marital_status like", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusNotLike(String value) {
            addCriterion("marital_status not like", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusIn(List<String> values) {
            addCriterion("marital_status in", values, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusNotIn(List<String> values) {
            addCriterion("marital_status not in", values, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusBetween(String value1, String value2) {
            addCriterion("marital_status between", value1, value2, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusNotBetween(String value1, String value2) {
            addCriterion("marital_status not between", value1, value2, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andChildrenStatusIsNull() {
            addCriterion("children_status is null");
            return (Criteria) this;
        }

        public Criteria andChildrenStatusIsNotNull() {
            addCriterion("children_status is not null");
            return (Criteria) this;
        }

        public Criteria andChildrenStatusEqualTo(String value) {
            addCriterion("children_status =", value, "childrenStatus");
            return (Criteria) this;
        }

        public Criteria andChildrenStatusNotEqualTo(String value) {
            addCriterion("children_status <>", value, "childrenStatus");
            return (Criteria) this;
        }

        public Criteria andChildrenStatusGreaterThan(String value) {
            addCriterion("children_status >", value, "childrenStatus");
            return (Criteria) this;
        }

        public Criteria andChildrenStatusGreaterThanOrEqualTo(String value) {
            addCriterion("children_status >=", value, "childrenStatus");
            return (Criteria) this;
        }

        public Criteria andChildrenStatusLessThan(String value) {
            addCriterion("children_status <", value, "childrenStatus");
            return (Criteria) this;
        }

        public Criteria andChildrenStatusLessThanOrEqualTo(String value) {
            addCriterion("children_status <=", value, "childrenStatus");
            return (Criteria) this;
        }

        public Criteria andChildrenStatusLike(String value) {
            addCriterion("children_status like", value, "childrenStatus");
            return (Criteria) this;
        }

        public Criteria andChildrenStatusNotLike(String value) {
            addCriterion("children_status not like", value, "childrenStatus");
            return (Criteria) this;
        }

        public Criteria andChildrenStatusIn(List<String> values) {
            addCriterion("children_status in", values, "childrenStatus");
            return (Criteria) this;
        }

        public Criteria andChildrenStatusNotIn(List<String> values) {
            addCriterion("children_status not in", values, "childrenStatus");
            return (Criteria) this;
        }

        public Criteria andChildrenStatusBetween(String value1, String value2) {
            addCriterion("children_status between", value1, value2, "childrenStatus");
            return (Criteria) this;
        }

        public Criteria andChildrenStatusNotBetween(String value1, String value2) {
            addCriterion("children_status not between", value1, value2, "childrenStatus");
            return (Criteria) this;
        }

        public Criteria andEndowmentInsuranceStatusIsNull() {
            addCriterion("\"endowment insurance_status\" is null");
            return (Criteria) this;
        }

        public Criteria andEndowmentInsuranceStatusIsNotNull() {
            addCriterion("\"endowment insurance_status\" is not null");
            return (Criteria) this;
        }

        public Criteria andEndowmentInsuranceStatusEqualTo(String value) {
            addCriterion("\"endowment insurance_status\" =", value, "endowmentInsuranceStatus");
            return (Criteria) this;
        }

        public Criteria andEndowmentInsuranceStatusNotEqualTo(String value) {
            addCriterion("\"endowment insurance_status\" <>", value, "endowmentInsuranceStatus");
            return (Criteria) this;
        }

        public Criteria andEndowmentInsuranceStatusGreaterThan(String value) {
            addCriterion("\"endowment insurance_status\" >", value, "endowmentInsuranceStatus");
            return (Criteria) this;
        }

        public Criteria andEndowmentInsuranceStatusGreaterThanOrEqualTo(String value) {
            addCriterion("\"endowment insurance_status\" >=", value, "endowmentInsuranceStatus");
            return (Criteria) this;
        }

        public Criteria andEndowmentInsuranceStatusLessThan(String value) {
            addCriterion("\"endowment insurance_status\" <", value, "endowmentInsuranceStatus");
            return (Criteria) this;
        }

        public Criteria andEndowmentInsuranceStatusLessThanOrEqualTo(String value) {
            addCriterion("\"endowment insurance_status\" <=", value, "endowmentInsuranceStatus");
            return (Criteria) this;
        }

        public Criteria andEndowmentInsuranceStatusLike(String value) {
            addCriterion("\"endowment insurance_status\" like", value, "endowmentInsuranceStatus");
            return (Criteria) this;
        }

        public Criteria andEndowmentInsuranceStatusNotLike(String value) {
            addCriterion("\"endowment insurance_status\" not like", value, "endowmentInsuranceStatus");
            return (Criteria) this;
        }

        public Criteria andEndowmentInsuranceStatusIn(List<String> values) {
            addCriterion("\"endowment insurance_status\" in", values, "endowmentInsuranceStatus");
            return (Criteria) this;
        }

        public Criteria andEndowmentInsuranceStatusNotIn(List<String> values) {
            addCriterion("\"endowment insurance_status\" not in", values, "endowmentInsuranceStatus");
            return (Criteria) this;
        }

        public Criteria andEndowmentInsuranceStatusBetween(String value1, String value2) {
            addCriterion("\"endowment insurance_status\" between", value1, value2, "endowmentInsuranceStatus");
            return (Criteria) this;
        }

        public Criteria andEndowmentInsuranceStatusNotBetween(String value1, String value2) {
            addCriterion("\"endowment insurance_status\" not between", value1, value2, "endowmentInsuranceStatus");
            return (Criteria) this;
        }

        public Criteria andLifeInsuranceStatusIsNull() {
            addCriterion("life_insurance_status is null");
            return (Criteria) this;
        }

        public Criteria andLifeInsuranceStatusIsNotNull() {
            addCriterion("life_insurance_status is not null");
            return (Criteria) this;
        }

        public Criteria andLifeInsuranceStatusEqualTo(String value) {
            addCriterion("life_insurance_status =", value, "lifeInsuranceStatus");
            return (Criteria) this;
        }

        public Criteria andLifeInsuranceStatusNotEqualTo(String value) {
            addCriterion("life_insurance_status <>", value, "lifeInsuranceStatus");
            return (Criteria) this;
        }

        public Criteria andLifeInsuranceStatusGreaterThan(String value) {
            addCriterion("life_insurance_status >", value, "lifeInsuranceStatus");
            return (Criteria) this;
        }

        public Criteria andLifeInsuranceStatusGreaterThanOrEqualTo(String value) {
            addCriterion("life_insurance_status >=", value, "lifeInsuranceStatus");
            return (Criteria) this;
        }

        public Criteria andLifeInsuranceStatusLessThan(String value) {
            addCriterion("life_insurance_status <", value, "lifeInsuranceStatus");
            return (Criteria) this;
        }

        public Criteria andLifeInsuranceStatusLessThanOrEqualTo(String value) {
            addCriterion("life_insurance_status <=", value, "lifeInsuranceStatus");
            return (Criteria) this;
        }

        public Criteria andLifeInsuranceStatusLike(String value) {
            addCriterion("life_insurance_status like", value, "lifeInsuranceStatus");
            return (Criteria) this;
        }

        public Criteria andLifeInsuranceStatusNotLike(String value) {
            addCriterion("life_insurance_status not like", value, "lifeInsuranceStatus");
            return (Criteria) this;
        }

        public Criteria andLifeInsuranceStatusIn(List<String> values) {
            addCriterion("life_insurance_status in", values, "lifeInsuranceStatus");
            return (Criteria) this;
        }

        public Criteria andLifeInsuranceStatusNotIn(List<String> values) {
            addCriterion("life_insurance_status not in", values, "lifeInsuranceStatus");
            return (Criteria) this;
        }

        public Criteria andLifeInsuranceStatusBetween(String value1, String value2) {
            addCriterion("life_insurance_status between", value1, value2, "lifeInsuranceStatus");
            return (Criteria) this;
        }

        public Criteria andLifeInsuranceStatusNotBetween(String value1, String value2) {
            addCriterion("life_insurance_status not between", value1, value2, "lifeInsuranceStatus");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeIsNull() {
            addCriterion("employment_type is null");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeIsNotNull() {
            addCriterion("employment_type is not null");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeEqualTo(String value) {
            addCriterion("employment_type =", value, "employmentType");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeNotEqualTo(String value) {
            addCriterion("employment_type <>", value, "employmentType");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeGreaterThan(String value) {
            addCriterion("employment_type >", value, "employmentType");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeGreaterThanOrEqualTo(String value) {
            addCriterion("employment_type >=", value, "employmentType");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeLessThan(String value) {
            addCriterion("employment_type <", value, "employmentType");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeLessThanOrEqualTo(String value) {
            addCriterion("employment_type <=", value, "employmentType");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeLike(String value) {
            addCriterion("employment_type like", value, "employmentType");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeNotLike(String value) {
            addCriterion("employment_type not like", value, "employmentType");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeIn(List<String> values) {
            addCriterion("employment_type in", values, "employmentType");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeNotIn(List<String> values) {
            addCriterion("employment_type not in", values, "employmentType");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeBetween(String value1, String value2) {
            addCriterion("employment_type between", value1, value2, "employmentType");
            return (Criteria) this;
        }

        public Criteria andEmploymentTypeNotBetween(String value1, String value2) {
            addCriterion("employment_type not between", value1, value2, "employmentType");
            return (Criteria) this;
        }

        public Criteria andHighestEducationIsNull() {
            addCriterion("highest_education is null");
            return (Criteria) this;
        }

        public Criteria andHighestEducationIsNotNull() {
            addCriterion("highest_education is not null");
            return (Criteria) this;
        }

        public Criteria andHighestEducationEqualTo(String value) {
            addCriterion("highest_education =", value, "highestEducation");
            return (Criteria) this;
        }

        public Criteria andHighestEducationNotEqualTo(String value) {
            addCriterion("highest_education <>", value, "highestEducation");
            return (Criteria) this;
        }

        public Criteria andHighestEducationGreaterThan(String value) {
            addCriterion("highest_education >", value, "highestEducation");
            return (Criteria) this;
        }

        public Criteria andHighestEducationGreaterThanOrEqualTo(String value) {
            addCriterion("highest_education >=", value, "highestEducation");
            return (Criteria) this;
        }

        public Criteria andHighestEducationLessThan(String value) {
            addCriterion("highest_education <", value, "highestEducation");
            return (Criteria) this;
        }

        public Criteria andHighestEducationLessThanOrEqualTo(String value) {
            addCriterion("highest_education <=", value, "highestEducation");
            return (Criteria) this;
        }

        public Criteria andHighestEducationLike(String value) {
            addCriterion("highest_education like", value, "highestEducation");
            return (Criteria) this;
        }

        public Criteria andHighestEducationNotLike(String value) {
            addCriterion("highest_education not like", value, "highestEducation");
            return (Criteria) this;
        }

        public Criteria andHighestEducationIn(List<String> values) {
            addCriterion("highest_education in", values, "highestEducation");
            return (Criteria) this;
        }

        public Criteria andHighestEducationNotIn(List<String> values) {
            addCriterion("highest_education not in", values, "highestEducation");
            return (Criteria) this;
        }

        public Criteria andHighestEducationBetween(String value1, String value2) {
            addCriterion("highest_education between", value1, value2, "highestEducation");
            return (Criteria) this;
        }

        public Criteria andHighestEducationNotBetween(String value1, String value2) {
            addCriterion("highest_education not between", value1, value2, "highestEducation");
            return (Criteria) this;
        }

        public Criteria andResidenceAddressIsNull() {
            addCriterion("residence_address is null");
            return (Criteria) this;
        }

        public Criteria andResidenceAddressIsNotNull() {
            addCriterion("residence_address is not null");
            return (Criteria) this;
        }

        public Criteria andResidenceAddressEqualTo(String value) {
            addCriterion("residence_address =", value, "residenceAddress");
            return (Criteria) this;
        }

        public Criteria andResidenceAddressNotEqualTo(String value) {
            addCriterion("residence_address <>", value, "residenceAddress");
            return (Criteria) this;
        }

        public Criteria andResidenceAddressGreaterThan(String value) {
            addCriterion("residence_address >", value, "residenceAddress");
            return (Criteria) this;
        }

        public Criteria andResidenceAddressGreaterThanOrEqualTo(String value) {
            addCriterion("residence_address >=", value, "residenceAddress");
            return (Criteria) this;
        }

        public Criteria andResidenceAddressLessThan(String value) {
            addCriterion("residence_address <", value, "residenceAddress");
            return (Criteria) this;
        }

        public Criteria andResidenceAddressLessThanOrEqualTo(String value) {
            addCriterion("residence_address <=", value, "residenceAddress");
            return (Criteria) this;
        }

        public Criteria andResidenceAddressLike(String value) {
            addCriterion("residence_address like", value, "residenceAddress");
            return (Criteria) this;
        }

        public Criteria andResidenceAddressNotLike(String value) {
            addCriterion("residence_address not like", value, "residenceAddress");
            return (Criteria) this;
        }

        public Criteria andResidenceAddressIn(List<String> values) {
            addCriterion("residence_address in", values, "residenceAddress");
            return (Criteria) this;
        }

        public Criteria andResidenceAddressNotIn(List<String> values) {
            addCriterion("residence_address not in", values, "residenceAddress");
            return (Criteria) this;
        }

        public Criteria andResidenceAddressBetween(String value1, String value2) {
            addCriterion("residence_address between", value1, value2, "residenceAddress");
            return (Criteria) this;
        }

        public Criteria andResidenceAddressNotBetween(String value1, String value2) {
            addCriterion("residence_address not between", value1, value2, "residenceAddress");
            return (Criteria) this;
        }

        public Criteria andCertificateAddressIsNull() {
            addCriterion("certificate_address is null");
            return (Criteria) this;
        }

        public Criteria andCertificateAddressIsNotNull() {
            addCriterion("certificate_address is not null");
            return (Criteria) this;
        }

        public Criteria andCertificateAddressEqualTo(String value) {
            addCriterion("certificate_address =", value, "certificateAddress");
            return (Criteria) this;
        }

        public Criteria andCertificateAddressNotEqualTo(String value) {
            addCriterion("certificate_address <>", value, "certificateAddress");
            return (Criteria) this;
        }

        public Criteria andCertificateAddressGreaterThan(String value) {
            addCriterion("certificate_address >", value, "certificateAddress");
            return (Criteria) this;
        }

        public Criteria andCertificateAddressGreaterThanOrEqualTo(String value) {
            addCriterion("certificate_address >=", value, "certificateAddress");
            return (Criteria) this;
        }

        public Criteria andCertificateAddressLessThan(String value) {
            addCriterion("certificate_address <", value, "certificateAddress");
            return (Criteria) this;
        }

        public Criteria andCertificateAddressLessThanOrEqualTo(String value) {
            addCriterion("certificate_address <=", value, "certificateAddress");
            return (Criteria) this;
        }

        public Criteria andCertificateAddressLike(String value) {
            addCriterion("certificate_address like", value, "certificateAddress");
            return (Criteria) this;
        }

        public Criteria andCertificateAddressNotLike(String value) {
            addCriterion("certificate_address not like", value, "certificateAddress");
            return (Criteria) this;
        }

        public Criteria andCertificateAddressIn(List<String> values) {
            addCriterion("certificate_address in", values, "certificateAddress");
            return (Criteria) this;
        }

        public Criteria andCertificateAddressNotIn(List<String> values) {
            addCriterion("certificate_address not in", values, "certificateAddress");
            return (Criteria) this;
        }

        public Criteria andCertificateAddressBetween(String value1, String value2) {
            addCriterion("certificate_address between", value1, value2, "certificateAddress");
            return (Criteria) this;
        }

        public Criteria andCertificateAddressNotBetween(String value1, String value2) {
            addCriterion("certificate_address not between", value1, value2, "certificateAddress");
            return (Criteria) this;
        }

        public Criteria andRegisterDescIsNull() {
            addCriterion("register_desc is null");
            return (Criteria) this;
        }

        public Criteria andRegisterDescIsNotNull() {
            addCriterion("register_desc is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterDescEqualTo(String value) {
            addCriterion("register_desc =", value, "registerDesc");
            return (Criteria) this;
        }

        public Criteria andRegisterDescNotEqualTo(String value) {
            addCriterion("register_desc <>", value, "registerDesc");
            return (Criteria) this;
        }

        public Criteria andRegisterDescGreaterThan(String value) {
            addCriterion("register_desc >", value, "registerDesc");
            return (Criteria) this;
        }

        public Criteria andRegisterDescGreaterThanOrEqualTo(String value) {
            addCriterion("register_desc >=", value, "registerDesc");
            return (Criteria) this;
        }

        public Criteria andRegisterDescLessThan(String value) {
            addCriterion("register_desc <", value, "registerDesc");
            return (Criteria) this;
        }

        public Criteria andRegisterDescLessThanOrEqualTo(String value) {
            addCriterion("register_desc <=", value, "registerDesc");
            return (Criteria) this;
        }

        public Criteria andRegisterDescLike(String value) {
            addCriterion("register_desc like", value, "registerDesc");
            return (Criteria) this;
        }

        public Criteria andRegisterDescNotLike(String value) {
            addCriterion("register_desc not like", value, "registerDesc");
            return (Criteria) this;
        }

        public Criteria andRegisterDescIn(List<String> values) {
            addCriterion("register_desc in", values, "registerDesc");
            return (Criteria) this;
        }

        public Criteria andRegisterDescNotIn(List<String> values) {
            addCriterion("register_desc not in", values, "registerDesc");
            return (Criteria) this;
        }

        public Criteria andRegisterDescBetween(String value1, String value2) {
            addCriterion("register_desc between", value1, value2, "registerDesc");
            return (Criteria) this;
        }

        public Criteria andRegisterDescNotBetween(String value1, String value2) {
            addCriterion("register_desc not between", value1, value2, "registerDesc");
            return (Criteria) this;
        }

        public Criteria andFrozenStatusIsNull() {
            addCriterion("frozen_status is null");
            return (Criteria) this;
        }

        public Criteria andFrozenStatusIsNotNull() {
            addCriterion("frozen_status is not null");
            return (Criteria) this;
        }

        public Criteria andFrozenStatusEqualTo(String value) {
            addCriterion("frozen_status =", value, "frozenStatus");
            return (Criteria) this;
        }

        public Criteria andFrozenStatusNotEqualTo(String value) {
            addCriterion("frozen_status <>", value, "frozenStatus");
            return (Criteria) this;
        }

        public Criteria andFrozenStatusGreaterThan(String value) {
            addCriterion("frozen_status >", value, "frozenStatus");
            return (Criteria) this;
        }

        public Criteria andFrozenStatusGreaterThanOrEqualTo(String value) {
            addCriterion("frozen_status >=", value, "frozenStatus");
            return (Criteria) this;
        }

        public Criteria andFrozenStatusLessThan(String value) {
            addCriterion("frozen_status <", value, "frozenStatus");
            return (Criteria) this;
        }

        public Criteria andFrozenStatusLessThanOrEqualTo(String value) {
            addCriterion("frozen_status <=", value, "frozenStatus");
            return (Criteria) this;
        }

        public Criteria andFrozenStatusLike(String value) {
            addCriterion("frozen_status like", value, "frozenStatus");
            return (Criteria) this;
        }

        public Criteria andFrozenStatusNotLike(String value) {
            addCriterion("frozen_status not like", value, "frozenStatus");
            return (Criteria) this;
        }

        public Criteria andFrozenStatusIn(List<String> values) {
            addCriterion("frozen_status in", values, "frozenStatus");
            return (Criteria) this;
        }

        public Criteria andFrozenStatusNotIn(List<String> values) {
            addCriterion("frozen_status not in", values, "frozenStatus");
            return (Criteria) this;
        }

        public Criteria andFrozenStatusBetween(String value1, String value2) {
            addCriterion("frozen_status between", value1, value2, "frozenStatus");
            return (Criteria) this;
        }

        public Criteria andFrozenStatusNotBetween(String value1, String value2) {
            addCriterion("frozen_status not between", value1, value2, "frozenStatus");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneNameIsNull() {
            addCriterion("derict_relations_one_name is null");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneNameIsNotNull() {
            addCriterion("derict_relations_one_name is not null");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneNameEqualTo(String value) {
            addCriterion("derict_relations_one_name =", value, "derictRelationsOneName");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneNameNotEqualTo(String value) {
            addCriterion("derict_relations_one_name <>", value, "derictRelationsOneName");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneNameGreaterThan(String value) {
            addCriterion("derict_relations_one_name >", value, "derictRelationsOneName");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneNameGreaterThanOrEqualTo(String value) {
            addCriterion("derict_relations_one_name >=", value, "derictRelationsOneName");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneNameLessThan(String value) {
            addCriterion("derict_relations_one_name <", value, "derictRelationsOneName");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneNameLessThanOrEqualTo(String value) {
            addCriterion("derict_relations_one_name <=", value, "derictRelationsOneName");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneNameLike(String value) {
            addCriterion("derict_relations_one_name like", value, "derictRelationsOneName");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneNameNotLike(String value) {
            addCriterion("derict_relations_one_name not like", value, "derictRelationsOneName");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneNameIn(List<String> values) {
            addCriterion("derict_relations_one_name in", values, "derictRelationsOneName");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneNameNotIn(List<String> values) {
            addCriterion("derict_relations_one_name not in", values, "derictRelationsOneName");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneNameBetween(String value1, String value2) {
            addCriterion("derict_relations_one_name between", value1, value2, "derictRelationsOneName");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneNameNotBetween(String value1, String value2) {
            addCriterion("derict_relations_one_name not between", value1, value2, "derictRelationsOneName");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneIdIsNull() {
            addCriterion("derict_relations_one_id is null");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneIdIsNotNull() {
            addCriterion("derict_relations_one_id is not null");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneIdEqualTo(String value) {
            addCriterion("derict_relations_one_id =", value, "derictRelationsOneId");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneIdNotEqualTo(String value) {
            addCriterion("derict_relations_one_id <>", value, "derictRelationsOneId");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneIdGreaterThan(String value) {
            addCriterion("derict_relations_one_id >", value, "derictRelationsOneId");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneIdGreaterThanOrEqualTo(String value) {
            addCriterion("derict_relations_one_id >=", value, "derictRelationsOneId");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneIdLessThan(String value) {
            addCriterion("derict_relations_one_id <", value, "derictRelationsOneId");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneIdLessThanOrEqualTo(String value) {
            addCriterion("derict_relations_one_id <=", value, "derictRelationsOneId");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneIdLike(String value) {
            addCriterion("derict_relations_one_id like", value, "derictRelationsOneId");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneIdNotLike(String value) {
            addCriterion("derict_relations_one_id not like", value, "derictRelationsOneId");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneIdIn(List<String> values) {
            addCriterion("derict_relations_one_id in", values, "derictRelationsOneId");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneIdNotIn(List<String> values) {
            addCriterion("derict_relations_one_id not in", values, "derictRelationsOneId");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneIdBetween(String value1, String value2) {
            addCriterion("derict_relations_one_id between", value1, value2, "derictRelationsOneId");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOneIdNotBetween(String value1, String value2) {
            addCriterion("derict_relations_one_id not between", value1, value2, "derictRelationsOneId");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOnePhoneIsNull() {
            addCriterion("derict_relations_one_phone is null");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOnePhoneIsNotNull() {
            addCriterion("derict_relations_one_phone is not null");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOnePhoneEqualTo(String value) {
            addCriterion("derict_relations_one_phone =", value, "derictRelationsOnePhone");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOnePhoneNotEqualTo(String value) {
            addCriterion("derict_relations_one_phone <>", value, "derictRelationsOnePhone");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOnePhoneGreaterThan(String value) {
            addCriterion("derict_relations_one_phone >", value, "derictRelationsOnePhone");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOnePhoneGreaterThanOrEqualTo(String value) {
            addCriterion("derict_relations_one_phone >=", value, "derictRelationsOnePhone");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOnePhoneLessThan(String value) {
            addCriterion("derict_relations_one_phone <", value, "derictRelationsOnePhone");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOnePhoneLessThanOrEqualTo(String value) {
            addCriterion("derict_relations_one_phone <=", value, "derictRelationsOnePhone");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOnePhoneLike(String value) {
            addCriterion("derict_relations_one_phone like", value, "derictRelationsOnePhone");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOnePhoneNotLike(String value) {
            addCriterion("derict_relations_one_phone not like", value, "derictRelationsOnePhone");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOnePhoneIn(List<String> values) {
            addCriterion("derict_relations_one_phone in", values, "derictRelationsOnePhone");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOnePhoneNotIn(List<String> values) {
            addCriterion("derict_relations_one_phone not in", values, "derictRelationsOnePhone");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOnePhoneBetween(String value1, String value2) {
            addCriterion("derict_relations_one_phone between", value1, value2, "derictRelationsOnePhone");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsOnePhoneNotBetween(String value1, String value2) {
            addCriterion("derict_relations_one_phone not between", value1, value2, "derictRelationsOnePhone");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoNameIsNull() {
            addCriterion("derict_relations_two_name is null");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoNameIsNotNull() {
            addCriterion("derict_relations_two_name is not null");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoNameEqualTo(String value) {
            addCriterion("derict_relations_two_name =", value, "derictRelationsTwoName");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoNameNotEqualTo(String value) {
            addCriterion("derict_relations_two_name <>", value, "derictRelationsTwoName");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoNameGreaterThan(String value) {
            addCriterion("derict_relations_two_name >", value, "derictRelationsTwoName");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoNameGreaterThanOrEqualTo(String value) {
            addCriterion("derict_relations_two_name >=", value, "derictRelationsTwoName");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoNameLessThan(String value) {
            addCriterion("derict_relations_two_name <", value, "derictRelationsTwoName");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoNameLessThanOrEqualTo(String value) {
            addCriterion("derict_relations_two_name <=", value, "derictRelationsTwoName");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoNameLike(String value) {
            addCriterion("derict_relations_two_name like", value, "derictRelationsTwoName");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoNameNotLike(String value) {
            addCriterion("derict_relations_two_name not like", value, "derictRelationsTwoName");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoNameIn(List<String> values) {
            addCriterion("derict_relations_two_name in", values, "derictRelationsTwoName");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoNameNotIn(List<String> values) {
            addCriterion("derict_relations_two_name not in", values, "derictRelationsTwoName");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoNameBetween(String value1, String value2) {
            addCriterion("derict_relations_two_name between", value1, value2, "derictRelationsTwoName");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoNameNotBetween(String value1, String value2) {
            addCriterion("derict_relations_two_name not between", value1, value2, "derictRelationsTwoName");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoIdIsNull() {
            addCriterion("derict_relations_two_id is null");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoIdIsNotNull() {
            addCriterion("derict_relations_two_id is not null");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoIdEqualTo(String value) {
            addCriterion("derict_relations_two_id =", value, "derictRelationsTwoId");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoIdNotEqualTo(String value) {
            addCriterion("derict_relations_two_id <>", value, "derictRelationsTwoId");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoIdGreaterThan(String value) {
            addCriterion("derict_relations_two_id >", value, "derictRelationsTwoId");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoIdGreaterThanOrEqualTo(String value) {
            addCriterion("derict_relations_two_id >=", value, "derictRelationsTwoId");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoIdLessThan(String value) {
            addCriterion("derict_relations_two_id <", value, "derictRelationsTwoId");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoIdLessThanOrEqualTo(String value) {
            addCriterion("derict_relations_two_id <=", value, "derictRelationsTwoId");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoIdLike(String value) {
            addCriterion("derict_relations_two_id like", value, "derictRelationsTwoId");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoIdNotLike(String value) {
            addCriterion("derict_relations_two_id not like", value, "derictRelationsTwoId");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoIdIn(List<String> values) {
            addCriterion("derict_relations_two_id in", values, "derictRelationsTwoId");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoIdNotIn(List<String> values) {
            addCriterion("derict_relations_two_id not in", values, "derictRelationsTwoId");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoIdBetween(String value1, String value2) {
            addCriterion("derict_relations_two_id between", value1, value2, "derictRelationsTwoId");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoIdNotBetween(String value1, String value2) {
            addCriterion("derict_relations_two_id not between", value1, value2, "derictRelationsTwoId");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoPhoneIsNull() {
            addCriterion("derict_relations_two_phone is null");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoPhoneIsNotNull() {
            addCriterion("derict_relations_two_phone is not null");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoPhoneEqualTo(String value) {
            addCriterion("derict_relations_two_phone =", value, "derictRelationsTwoPhone");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoPhoneNotEqualTo(String value) {
            addCriterion("derict_relations_two_phone <>", value, "derictRelationsTwoPhone");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoPhoneGreaterThan(String value) {
            addCriterion("derict_relations_two_phone >", value, "derictRelationsTwoPhone");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("derict_relations_two_phone >=", value, "derictRelationsTwoPhone");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoPhoneLessThan(String value) {
            addCriterion("derict_relations_two_phone <", value, "derictRelationsTwoPhone");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoPhoneLessThanOrEqualTo(String value) {
            addCriterion("derict_relations_two_phone <=", value, "derictRelationsTwoPhone");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoPhoneLike(String value) {
            addCriterion("derict_relations_two_phone like", value, "derictRelationsTwoPhone");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoPhoneNotLike(String value) {
            addCriterion("derict_relations_two_phone not like", value, "derictRelationsTwoPhone");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoPhoneIn(List<String> values) {
            addCriterion("derict_relations_two_phone in", values, "derictRelationsTwoPhone");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoPhoneNotIn(List<String> values) {
            addCriterion("derict_relations_two_phone not in", values, "derictRelationsTwoPhone");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoPhoneBetween(String value1, String value2) {
            addCriterion("derict_relations_two_phone between", value1, value2, "derictRelationsTwoPhone");
            return (Criteria) this;
        }

        public Criteria andDerictRelationsTwoPhoneNotBetween(String value1, String value2) {
            addCriterion("derict_relations_two_phone not between", value1, value2, "derictRelationsTwoPhone");
            return (Criteria) this;
        }

        public Criteria andRelationsOneNameIsNull() {
            addCriterion("relations_one_name is null");
            return (Criteria) this;
        }

        public Criteria andRelationsOneNameIsNotNull() {
            addCriterion("relations_one_name is not null");
            return (Criteria) this;
        }

        public Criteria andRelationsOneNameEqualTo(String value) {
            addCriterion("relations_one_name =", value, "relationsOneName");
            return (Criteria) this;
        }

        public Criteria andRelationsOneNameNotEqualTo(String value) {
            addCriterion("relations_one_name <>", value, "relationsOneName");
            return (Criteria) this;
        }

        public Criteria andRelationsOneNameGreaterThan(String value) {
            addCriterion("relations_one_name >", value, "relationsOneName");
            return (Criteria) this;
        }

        public Criteria andRelationsOneNameGreaterThanOrEqualTo(String value) {
            addCriterion("relations_one_name >=", value, "relationsOneName");
            return (Criteria) this;
        }

        public Criteria andRelationsOneNameLessThan(String value) {
            addCriterion("relations_one_name <", value, "relationsOneName");
            return (Criteria) this;
        }

        public Criteria andRelationsOneNameLessThanOrEqualTo(String value) {
            addCriterion("relations_one_name <=", value, "relationsOneName");
            return (Criteria) this;
        }

        public Criteria andRelationsOneNameLike(String value) {
            addCriterion("relations_one_name like", value, "relationsOneName");
            return (Criteria) this;
        }

        public Criteria andRelationsOneNameNotLike(String value) {
            addCriterion("relations_one_name not like", value, "relationsOneName");
            return (Criteria) this;
        }

        public Criteria andRelationsOneNameIn(List<String> values) {
            addCriterion("relations_one_name in", values, "relationsOneName");
            return (Criteria) this;
        }

        public Criteria andRelationsOneNameNotIn(List<String> values) {
            addCriterion("relations_one_name not in", values, "relationsOneName");
            return (Criteria) this;
        }

        public Criteria andRelationsOneNameBetween(String value1, String value2) {
            addCriterion("relations_one_name between", value1, value2, "relationsOneName");
            return (Criteria) this;
        }

        public Criteria andRelationsOneNameNotBetween(String value1, String value2) {
            addCriterion("relations_one_name not between", value1, value2, "relationsOneName");
            return (Criteria) this;
        }

        public Criteria andRelationsOneIdIsNull() {
            addCriterion("relations_one_id is null");
            return (Criteria) this;
        }

        public Criteria andRelationsOneIdIsNotNull() {
            addCriterion("relations_one_id is not null");
            return (Criteria) this;
        }

        public Criteria andRelationsOneIdEqualTo(String value) {
            addCriterion("relations_one_id =", value, "relationsOneId");
            return (Criteria) this;
        }

        public Criteria andRelationsOneIdNotEqualTo(String value) {
            addCriterion("relations_one_id <>", value, "relationsOneId");
            return (Criteria) this;
        }

        public Criteria andRelationsOneIdGreaterThan(String value) {
            addCriterion("relations_one_id >", value, "relationsOneId");
            return (Criteria) this;
        }

        public Criteria andRelationsOneIdGreaterThanOrEqualTo(String value) {
            addCriterion("relations_one_id >=", value, "relationsOneId");
            return (Criteria) this;
        }

        public Criteria andRelationsOneIdLessThan(String value) {
            addCriterion("relations_one_id <", value, "relationsOneId");
            return (Criteria) this;
        }

        public Criteria andRelationsOneIdLessThanOrEqualTo(String value) {
            addCriterion("relations_one_id <=", value, "relationsOneId");
            return (Criteria) this;
        }

        public Criteria andRelationsOneIdLike(String value) {
            addCriterion("relations_one_id like", value, "relationsOneId");
            return (Criteria) this;
        }

        public Criteria andRelationsOneIdNotLike(String value) {
            addCriterion("relations_one_id not like", value, "relationsOneId");
            return (Criteria) this;
        }

        public Criteria andRelationsOneIdIn(List<String> values) {
            addCriterion("relations_one_id in", values, "relationsOneId");
            return (Criteria) this;
        }

        public Criteria andRelationsOneIdNotIn(List<String> values) {
            addCriterion("relations_one_id not in", values, "relationsOneId");
            return (Criteria) this;
        }

        public Criteria andRelationsOneIdBetween(String value1, String value2) {
            addCriterion("relations_one_id between", value1, value2, "relationsOneId");
            return (Criteria) this;
        }

        public Criteria andRelationsOneIdNotBetween(String value1, String value2) {
            addCriterion("relations_one_id not between", value1, value2, "relationsOneId");
            return (Criteria) this;
        }

        public Criteria andRelationsOnePhoneIsNull() {
            addCriterion("relations_one_phone is null");
            return (Criteria) this;
        }

        public Criteria andRelationsOnePhoneIsNotNull() {
            addCriterion("relations_one_phone is not null");
            return (Criteria) this;
        }

        public Criteria andRelationsOnePhoneEqualTo(String value) {
            addCriterion("relations_one_phone =", value, "relationsOnePhone");
            return (Criteria) this;
        }

        public Criteria andRelationsOnePhoneNotEqualTo(String value) {
            addCriterion("relations_one_phone <>", value, "relationsOnePhone");
            return (Criteria) this;
        }

        public Criteria andRelationsOnePhoneGreaterThan(String value) {
            addCriterion("relations_one_phone >", value, "relationsOnePhone");
            return (Criteria) this;
        }

        public Criteria andRelationsOnePhoneGreaterThanOrEqualTo(String value) {
            addCriterion("relations_one_phone >=", value, "relationsOnePhone");
            return (Criteria) this;
        }

        public Criteria andRelationsOnePhoneLessThan(String value) {
            addCriterion("relations_one_phone <", value, "relationsOnePhone");
            return (Criteria) this;
        }

        public Criteria andRelationsOnePhoneLessThanOrEqualTo(String value) {
            addCriterion("relations_one_phone <=", value, "relationsOnePhone");
            return (Criteria) this;
        }

        public Criteria andRelationsOnePhoneLike(String value) {
            addCriterion("relations_one_phone like", value, "relationsOnePhone");
            return (Criteria) this;
        }

        public Criteria andRelationsOnePhoneNotLike(String value) {
            addCriterion("relations_one_phone not like", value, "relationsOnePhone");
            return (Criteria) this;
        }

        public Criteria andRelationsOnePhoneIn(List<String> values) {
            addCriterion("relations_one_phone in", values, "relationsOnePhone");
            return (Criteria) this;
        }

        public Criteria andRelationsOnePhoneNotIn(List<String> values) {
            addCriterion("relations_one_phone not in", values, "relationsOnePhone");
            return (Criteria) this;
        }

        public Criteria andRelationsOnePhoneBetween(String value1, String value2) {
            addCriterion("relations_one_phone between", value1, value2, "relationsOnePhone");
            return (Criteria) this;
        }

        public Criteria andRelationsOnePhoneNotBetween(String value1, String value2) {
            addCriterion("relations_one_phone not between", value1, value2, "relationsOnePhone");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoNameIsNull() {
            addCriterion("relations_two_name is null");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoNameIsNotNull() {
            addCriterion("relations_two_name is not null");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoNameEqualTo(String value) {
            addCriterion("relations_two_name =", value, "relationsTwoName");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoNameNotEqualTo(String value) {
            addCriterion("relations_two_name <>", value, "relationsTwoName");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoNameGreaterThan(String value) {
            addCriterion("relations_two_name >", value, "relationsTwoName");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoNameGreaterThanOrEqualTo(String value) {
            addCriterion("relations_two_name >=", value, "relationsTwoName");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoNameLessThan(String value) {
            addCriterion("relations_two_name <", value, "relationsTwoName");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoNameLessThanOrEqualTo(String value) {
            addCriterion("relations_two_name <=", value, "relationsTwoName");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoNameLike(String value) {
            addCriterion("relations_two_name like", value, "relationsTwoName");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoNameNotLike(String value) {
            addCriterion("relations_two_name not like", value, "relationsTwoName");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoNameIn(List<String> values) {
            addCriterion("relations_two_name in", values, "relationsTwoName");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoNameNotIn(List<String> values) {
            addCriterion("relations_two_name not in", values, "relationsTwoName");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoNameBetween(String value1, String value2) {
            addCriterion("relations_two_name between", value1, value2, "relationsTwoName");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoNameNotBetween(String value1, String value2) {
            addCriterion("relations_two_name not between", value1, value2, "relationsTwoName");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoIdIsNull() {
            addCriterion("relations_two_id is null");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoIdIsNotNull() {
            addCriterion("relations_two_id is not null");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoIdEqualTo(String value) {
            addCriterion("relations_two_id =", value, "relationsTwoId");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoIdNotEqualTo(String value) {
            addCriterion("relations_two_id <>", value, "relationsTwoId");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoIdGreaterThan(String value) {
            addCriterion("relations_two_id >", value, "relationsTwoId");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoIdGreaterThanOrEqualTo(String value) {
            addCriterion("relations_two_id >=", value, "relationsTwoId");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoIdLessThan(String value) {
            addCriterion("relations_two_id <", value, "relationsTwoId");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoIdLessThanOrEqualTo(String value) {
            addCriterion("relations_two_id <=", value, "relationsTwoId");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoIdLike(String value) {
            addCriterion("relations_two_id like", value, "relationsTwoId");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoIdNotLike(String value) {
            addCriterion("relations_two_id not like", value, "relationsTwoId");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoIdIn(List<String> values) {
            addCriterion("relations_two_id in", values, "relationsTwoId");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoIdNotIn(List<String> values) {
            addCriterion("relations_two_id not in", values, "relationsTwoId");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoIdBetween(String value1, String value2) {
            addCriterion("relations_two_id between", value1, value2, "relationsTwoId");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoIdNotBetween(String value1, String value2) {
            addCriterion("relations_two_id not between", value1, value2, "relationsTwoId");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoPhoneIsNull() {
            addCriterion("relations_two_phone is null");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoPhoneIsNotNull() {
            addCriterion("relations_two_phone is not null");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoPhoneEqualTo(String value) {
            addCriterion("relations_two_phone =", value, "relationsTwoPhone");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoPhoneNotEqualTo(String value) {
            addCriterion("relations_two_phone <>", value, "relationsTwoPhone");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoPhoneGreaterThan(String value) {
            addCriterion("relations_two_phone >", value, "relationsTwoPhone");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("relations_two_phone >=", value, "relationsTwoPhone");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoPhoneLessThan(String value) {
            addCriterion("relations_two_phone <", value, "relationsTwoPhone");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoPhoneLessThanOrEqualTo(String value) {
            addCriterion("relations_two_phone <=", value, "relationsTwoPhone");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoPhoneLike(String value) {
            addCriterion("relations_two_phone like", value, "relationsTwoPhone");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoPhoneNotLike(String value) {
            addCriterion("relations_two_phone not like", value, "relationsTwoPhone");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoPhoneIn(List<String> values) {
            addCriterion("relations_two_phone in", values, "relationsTwoPhone");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoPhoneNotIn(List<String> values) {
            addCriterion("relations_two_phone not in", values, "relationsTwoPhone");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoPhoneBetween(String value1, String value2) {
            addCriterion("relations_two_phone between", value1, value2, "relationsTwoPhone");
            return (Criteria) this;
        }

        public Criteria andRelationsTwoPhoneNotBetween(String value1, String value2) {
            addCriterion("relations_two_phone not between", value1, value2, "relationsTwoPhone");
            return (Criteria) this;
        }

        public Criteria andCertificateNoIsNull() {
            addCriterion("certificate_no is null");
            return (Criteria) this;
        }

        public Criteria andCertificateNoIsNotNull() {
            addCriterion("certificate_no is not null");
            return (Criteria) this;
        }

        public Criteria andCertificateNoEqualTo(String value) {
            addCriterion("certificate_no =", value, "certificateNo");
            return (Criteria) this;
        }

        public Criteria andCertificateNoNotEqualTo(String value) {
            addCriterion("certificate_no <>", value, "certificateNo");
            return (Criteria) this;
        }

        public Criteria andCertificateNoGreaterThan(String value) {
            addCriterion("certificate_no >", value, "certificateNo");
            return (Criteria) this;
        }

        public Criteria andCertificateNoGreaterThanOrEqualTo(String value) {
            addCriterion("certificate_no >=", value, "certificateNo");
            return (Criteria) this;
        }

        public Criteria andCertificateNoLessThan(String value) {
            addCriterion("certificate_no <", value, "certificateNo");
            return (Criteria) this;
        }

        public Criteria andCertificateNoLessThanOrEqualTo(String value) {
            addCriterion("certificate_no <=", value, "certificateNo");
            return (Criteria) this;
        }

        public Criteria andCertificateNoLike(String value) {
            addCriterion("certificate_no like", value, "certificateNo");
            return (Criteria) this;
        }

        public Criteria andCertificateNoNotLike(String value) {
            addCriterion("certificate_no not like", value, "certificateNo");
            return (Criteria) this;
        }

        public Criteria andCertificateNoIn(List<String> values) {
            addCriterion("certificate_no in", values, "certificateNo");
            return (Criteria) this;
        }

        public Criteria andCertificateNoNotIn(List<String> values) {
            addCriterion("certificate_no not in", values, "certificateNo");
            return (Criteria) this;
        }

        public Criteria andCertificateNoBetween(String value1, String value2) {
            addCriterion("certificate_no between", value1, value2, "certificateNo");
            return (Criteria) this;
        }

        public Criteria andCertificateNoNotBetween(String value1, String value2) {
            addCriterion("certificate_no not between", value1, value2, "certificateNo");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNull() {
            addCriterion("real_name is null");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNotNull() {
            addCriterion("real_name is not null");
            return (Criteria) this;
        }

        public Criteria andRealNameEqualTo(String value) {
            addCriterion("real_name =", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotEqualTo(String value) {
            addCriterion("real_name <>", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThan(String value) {
            addCriterion("real_name >", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThanOrEqualTo(String value) {
            addCriterion("real_name >=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThan(String value) {
            addCriterion("real_name <", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThanOrEqualTo(String value) {
            addCriterion("real_name <=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLike(String value) {
            addCriterion("real_name like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotLike(String value) {
            addCriterion("real_name not like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameIn(List<String> values) {
            addCriterion("real_name in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotIn(List<String> values) {
            addCriterion("real_name not in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameBetween(String value1, String value2) {
            addCriterion("real_name between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotBetween(String value1, String value2) {
            addCriterion("real_name not between", value1, value2, "realName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table w_personal_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table w_personal_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}