package cn.com.loan.pojo;

public class WsendIdentyCodeLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sendIdentyCode_log.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sendIdentyCode_log.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sendIdentyCode_log.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sendIdentyCode_log.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sendIdentyCode_log.createtime
     *
     * @mbggenerated
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sendIdentyCode_log.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sendIdentyCode_log.resolve
     *
     * @mbggenerated
     */
    private String resolve;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sendIdentyCode_log.id
     *
     * @return the value of w_sendIdentyCode_log.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sendIdentyCode_log.id
     *
     * @param id the value for w_sendIdentyCode_log.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sendIdentyCode_log.phone
     *
     * @return the value of w_sendIdentyCode_log.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sendIdentyCode_log.phone
     *
     * @param phone the value for w_sendIdentyCode_log.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sendIdentyCode_log.code
     *
     * @return the value of w_sendIdentyCode_log.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sendIdentyCode_log.code
     *
     * @param code the value for w_sendIdentyCode_log.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sendIdentyCode_log.status
     *
     * @return the value of w_sendIdentyCode_log.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sendIdentyCode_log.status
     *
     * @param status the value for w_sendIdentyCode_log.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sendIdentyCode_log.createtime
     *
     * @return the value of w_sendIdentyCode_log.createtime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sendIdentyCode_log.createtime
     *
     * @param createtime the value for w_sendIdentyCode_log.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sendIdentyCode_log.uid
     *
     * @return the value of w_sendIdentyCode_log.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sendIdentyCode_log.uid
     *
     * @param uid the value for w_sendIdentyCode_log.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sendIdentyCode_log.resolve
     *
     * @return the value of w_sendIdentyCode_log.resolve
     *
     * @mbggenerated
     */
    public String getResolve() {
        return resolve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sendIdentyCode_log.resolve
     *
     * @param resolve the value for w_sendIdentyCode_log.resolve
     *
     * @mbggenerated
     */
    public void setResolve(String resolve) {
        this.resolve = resolve == null ? null : resolve.trim();
    }
}